package main

import (
	"flag"
	"fmt"
	"io"
	"strings"
)

const topLevelHelp = `sunbeams — virtual display EDID generator for Sunshine/Moonlight game streaming

USAGE:
  sunbeams <command> [flags]

COMMANDS:
  generate    Build the virtual-display EDID binary and helper scripts
  switch      Turn the virtual display on/off (for Sunshine Prep Commands)
  install     Guided installer: firmware file, kernel arg, systemd user service
  uninstall   Remove the EDID injection: kargs, firmware file, user service
  devices     List built-in device presets (TVs, monitors, tablets, handhelds)
  modes       List configured modes with pixel clock + DTD/xrandr classification
  config      Manage user config at ~/.config/sunbeams/config.toml
  version     Print version, commit, and build date
  help        Show this help (use 'sunbeams <command> --help' for per-command help)

TYPICAL WORKFLOW:
  1. sudo sunbeams install             # one-time: firmware, kargs, systemd unit
  2. reboot
  3. In Sunshine, set per-app Prep Commands:
       Do:   sunbeams switch on
       Undo: sunbeams switch off

COMMON INVOCATIONS:
  sunbeams generate                            # emit EDID + scripts into the current dir
  sunbeams generate -o /tmp/edid --validate    # write to /tmp/edid and run edid-decode
  sunbeams modes                               # inspect what modes the EDID advertises
  sunbeams devices                             # inspect built-in device presets
  sunbeams config init                         # seed a user config you can edit
  sunbeams config show                         # dump the merged config as TOML
  sunbeams switch on --width 3840 --height 2160 --fps 120 --hdr
  sunbeams switch off

CONFIGURATION:
  Defaults are embedded in the binary. Run 'sunbeams config init' to write a
  user override at ~/.config/sunbeams/config.toml; edit it to change modes,
  EDID identity, or device presets. User values merge on top of defaults.

ENVIRONMENT:
  SUNSHINE_CLIENT_WIDTH, SUNSHINE_CLIENT_HEIGHT, SUNSHINE_CLIENT_FPS, SUNSHINE_CLIENT_HDR
    Used by 'sunbeams switch on' when --width / --height / --fps / --hdr
    are omitted. Sunshine exports these automatically from the Moonlight client.

Issues and source: https://github.com/asdfgasfhsn/sunbeams
`

// subcommandHelp holds the non-flag help content for a subcommand.
// Flag docs are generated by flag.FlagSet.PrintDefaults.
type subcommandHelp struct {
	Name        string   // "generate"
	Synopsis    string   // "sunbeams generate [-o <dir>] [-c <config>] [--no-scripts] [--validate]"
	Summary     string   // first-line summary
	Description string   // multi-line prose (optional)
	Examples    []string // one per line, no leading "$"
}

// subcommandHelps registers help content for every subcommand that uses a
// FlagSet-driven help page. Simple subcommands (devices, modes, version)
// bypass this and print inline.
var subcommandHelps = map[string]subcommandHelp{
	"generate": {
		Name:     "generate",
		Synopsis: "sunbeams generate [-o <dir>] [-c <config>] [--no-scripts] [--validate]",
		Summary:  "Build the virtual-display EDID binary and helper scripts.",
		Description: "Produces three files in the output directory:\n" +
			"  virtual_display.bin    the EDID the GPU will load via firmware_class.path\n" +
			"  add_custom_modes.sh    xrandr modelines for high-refresh modes whose pixel\n" +
			"                         clock exceeds the EDID DTD ceiling (655 MHz)\n" +
			"  sunshine_commands.txt  reference snippets for Sunshine Prep Commands",
		Examples: []string{
			"sunbeams generate",
			"sunbeams generate -o /tmp/edid",
			"sunbeams generate --validate",
			"sunbeams generate --no-scripts -o /etc/firmware",
		},
	},
	"switch-on": {
		Name:     "switch on",
		Synopsis: "sunbeams switch on [--width N --height N --fps N] [--hdr|--no-hdr] [-c <config>]",
		Summary:  "Activate the virtual display and set mode to match the Moonlight client.",
		Description: "Uses kscreen-doctor (KDE Plasma/Wayland) to enable the virtual output and\n" +
			"select the best mode for the requested resolution/refresh/HDR state.\n" +
			"When --width/--height/--fps are omitted, reads SUNSHINE_CLIENT_* env vars\n" +
			"that Sunshine exports during a session.",
		Examples: []string{
			"sunbeams switch on --width 3840 --height 2160 --fps 120 --hdr",
			"sunbeams switch on   # (with SUNSHINE_CLIENT_* set by Sunshine)",
		},
	},
	"switch-off": {
		Name:        "switch off",
		Synopsis:    "sunbeams switch off",
		Summary:     "Deactivate the virtual display.",
		Description: "Calls kscreen-doctor to disable the virtual output.",
		Examples:    []string{"sunbeams switch off"},
	},
	"config-show": {
		Name:     "config show",
		Synopsis: "sunbeams config show [-c <config>]",
		Summary:  "Print the merged config (defaults + user overrides) as TOML.",
		Description: "Useful for verifying which modes, devices, and EDID parameters are\n" +
			"actually in effect after ~/.config/sunbeams/config.toml is merged on\n" +
			"top of the embedded defaults.",
		Examples: []string{
			"sunbeams config show",
			"sunbeams config show -c /tmp/my-override.toml",
		},
	},
	"devices": {
		Name:     "devices",
		Synopsis: "sunbeams devices",
		Summary:  "List built-in device presets.",
		Description: "Presets describe real hardware (TVs, monitors, tablets, handhelds) and\n" +
			"seed the mode list. Add or override them in ~/.config/sunbeams/config.toml.",
		Examples: []string{"sunbeams devices"},
	},
	"modes": {
		Name:     "modes",
		Synopsis: "sunbeams modes",
		Summary:  "List every configured mode with pixel clock and DTD/xrandr classification.",
		Description: "Modes with pixel clock <= 655 MHz are encoded as Detailed Timing\n" +
			"Descriptors inside the EDID. Higher-clock modes cannot fit in a DTD and\n" +
			"are emitted into add_custom_modes.sh as xrandr modelines instead.",
		Examples: []string{"sunbeams modes"},
	},
	"install": {
		Name:     "install",
		Synopsis: "sudo sunbeams install",
		Summary:  "Guided Bazzite installer (requires root, reboot afterwards).",
		Description: "Interactively:\n" +
			"  1. scans /sys/class/drm for the virtual-display connector\n" +
			"  2. writes the EDID and add_custom_modes.sh to /etc/firmware/\n" +
			"  3. injects the drm.edid_firmware kernel argument via rpm-ostree\n" +
			"  4. installs a systemd user service to apply xrandr modes on login\n" +
			"A reboot is required for the kernel arg to take effect.",
		Examples: []string{"sudo sunbeams install"},
	},
	"uninstall": {
		Name:     "uninstall",
		Synopsis: "sudo sunbeams uninstall [--connector <name>] [-y]",
		Summary:  "Remove a sunbeams EDID injection (requires root, reboot afterwards).",
		Description: "Interactively detects and removes what 'install' added:\n" +
			"  1. sunbeams kernel args (drm.edid_firmware, video, firmware_class.path)\n" +
			"  2. the EDID firmware file at /etc/firmware/edid.bin\n" +
			"  3. the systemd user service and xrandr mode script\n" +
			"Use --connector to remove kargs for a single output only (leaves the\n" +
			"shared firmware file and user service in place). Use -y to remove\n" +
			"everything detected without prompting. A reboot is required for kernel\n" +
			"arg changes to take effect.",
		Examples: []string{
			"sudo sunbeams uninstall",
			"sudo sunbeams uninstall --connector DP-2",
			"sudo sunbeams uninstall -y",
		},
	},
	"version": {
		Name:     "version",
		Synopsis: "sunbeams version",
		Summary:  "Print version, commit SHA, and build date.",
		Examples: []string{"sunbeams version"},
	},
}

// topLevelSwitchHelp is printed when `switch` is invoked without `on` or `off`.
const topLevelSwitchHelp = `sunbeams switch — turn the virtual display on or off

USAGE:
  sunbeams switch <on|off> [flags]

SUBCOMMANDS:
  on     Activate the virtual display at a requested resolution/refresh/HDR
  off    Deactivate the virtual display

Run 'sunbeams switch on --help' or 'sunbeams switch off --help' for details.
`

// topLevelConfigHelp is printed when `config` is invoked without a subcommand.
const topLevelConfigHelp = `sunbeams config — manage ~/.config/sunbeams/config.toml

USAGE:
  sunbeams config <init|show> [flags]

SUBCOMMANDS:
  init    Seed a user config file from the embedded defaults
  show    Print the merged config (defaults + user overrides) as TOML

EXAMPLES:
  sunbeams config init                 # creates ~/.config/sunbeams/config.toml
  sunbeams config show                 # prints merged config to stdout
  sunbeams config show -c my.toml      # merge a specific override file instead
`

// wantsHelp returns true if args contains a help-requesting token.
func wantsHelp(args []string) bool {
	for _, a := range args {
		if a == "-h" || a == "--help" || a == "help" {
			return true
		}
	}
	return false
}

// renderSubcommandHelp writes a rich help page to w using help and fs.
// fs may be nil for subcommands with no flags.
func renderSubcommandHelp(w io.Writer, help subcommandHelp, fs *flag.FlagSet) {
	p := func(format string, args ...any) {
		_, _ = fmt.Fprintf(w, format, args...)
	}
	p("sunbeams %s — %s\n\n", help.Name, help.Summary)
	p("USAGE:\n")
	p("  %s\n\n", help.Synopsis)

	if desc := strings.TrimSpace(help.Description); desc != "" {
		p("DESCRIPTION:\n")
		for _, line := range strings.Split(desc, "\n") {
			p("  %s\n", line)
		}
		p("\n")
	}

	if fs != nil && hasFlags(fs) {
		p("FLAGS:\n")
		fs.SetOutput(w)
		fs.PrintDefaults()
		p("\n")
	}

	if len(help.Examples) > 0 {
		p("EXAMPLES:\n")
		for _, ex := range help.Examples {
			p("  %s\n", ex)
		}
	}
}

func hasFlags(fs *flag.FlagSet) bool {
	any := false
	fs.VisitAll(func(*flag.Flag) { any = true })
	return any
}
